# Change these first
owner: SynerTech-Labs
repo: Uptime

sites:
  - name: Synertech labs
    url: https://synertech-labs.ch
    icon: https://synertech-labs.ch/favicon.ico
    
  - name: PrometheusAI
    url: https://prometheusai.ch
    icon : https://prometheusai.ch/logowhite.svg

  - name: Supabase Status
    url: https://status.supabase.com/api/v2/status.json
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"description":"All Systems Operational"'
    __dangerous__body_degraded_if_text_missing: '"indicator":"none"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  logoUrl: https://synertech-labs.ch/logo.avif
  name: Synertech
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
